env:
  ARCH: amd64

freebsd_instance:
  image_family: freebsd-13-1

task:
  timeout_in: 60m
  install_script:
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    - pkg install -y git
    - portsnap auto
  script:
    - find .
