env:
  ARCH: amd64

freebsd_instance:
  image_family: freebsd-13-1

task:
  timeout_in: 120m
  install_script:
    - pkg info
    - pkg remove -y curl
# above: remove curl/wget since they are not expected to be there by default
#    - portsnap auto > /tmp/portsnap-auto.log
  script:
    - cp -R ports/games/stockfish/* /usr/ports/games/stockfish
    - cd /usr/ports/games/stockfish && make
