env:
  ARCH: amd64

freebsd_instance:
  image_family: freebsd-14-2

task:
  timeout_in: 120m
  install_script:
    - pkg info
    - pkg remove -y -a
# above: remove all packages from the system except pkg to have a clean build machine
    - pkg install -y git
    - git clone --depth 1 https://github.com/freebsd/freebsd-ports.git /usr/ports
  script:
    - cp -R ports/games/stockfish/* /usr/ports/games/stockfish
    - cd /usr/ports/games/stockfish && make BATCH=yes
