env:
  ARCH: amd64
  ARCH: aarch64

freebsd_instance:
  image_family: freebsd-13-1
  image_family: freebsd-12-3
  image_family: freebsd-11-4

task:
  timeout_in: 120m
  install_script:
    - pkg info
    - pkg remove -y -a
# above: remove all packages from the system except pkg to have a clean build machine
#    - portsnap auto > /tmp/portsnap-auto.log
  script:
    - cp -R ports/games/stockfish/* /usr/ports/games/stockfish
    - cd /usr/ports/games/stockfish && make
